// Comprehensive menu data for Tarkari - Pure Veg Restaurant
// Dombivli East pricing: ₹150-350 per person range

export interface MenuItem {
  id: number;
  name: string;
  desc: string;
  price: number;
  category: string;
  type: string;
  image: string;
  isPopular?: boolean;
  isSpicy?: boolean;
}

// North Indian - Traditional Home-style
export const northIndianDishes: MenuItem[] = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    desc: "Creamy tomato gravy with cottage cheese cubes",
    price: 220,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 2,
    name: "Paneer Tikka",
    desc: "Marinated cottage cheese grilled to perfection",
    price: 240,
    category: "North Indian",
    type: "Starter",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 3,
    name: "Veg Kolhapuri",
    desc: "Spicy mixed vegetables in Kolhapuri style",
    price: 200,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isSpicy: true,
  },
  {
    id: 4,
    name: "Dal Tadka",
    desc: "Yellow lentils tempered with aromatic spices",
    price: 160,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 5,
    name: "Dal Fry",
    desc: "Slow-cooked lentils with onion and tomato",
    price: 150,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 6,
    name: "Chana Masala",
    desc: "Chickpeas in tangy tomato gravy",
    price: 180,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 7,
    name: "Aloo Mutter",
    desc: "Potato and peas in aromatic gravy",
    price: 170,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 8,
    name: "Bhendi Do Pyaza",
    desc: "Okra cooked with double onions",
    price: 190,
    category: "North Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 9,
    name: "Butter Naan",
    desc: "Leavened bread brushed with butter",
    price: 40,
    category: "North Indian",
    type: "Breads",
    image: "/Tarkari-image.png",
  },
  {
    id: 10,
    name: "Tandoori Roti",
    desc: "Whole wheat flatbread from tandoor",
    price: 25,
    category: "North Indian",
    type: "Breads",
    image: "/Tarkari-image.png",
  },
  {
    id: 11,
    name: "Kulcha",
    desc: "Soft leavened flatbread",
    price: 45,
    category: "North Indian",
    type: "Breads",
    image: "/Tarkari-image.png",
  },
  {
    id: 12,
    name: "Jeera Rice",
    desc: "Basmati rice tempered with cumin",
    price: 120,
    category: "North Indian",
    type: "Rice",
    image: "/Tarkari-image.png",
  },
];

// South Indian - Authentic Flavors
export const southIndianDishes: MenuItem[] = [
  {
    id: 101,
    name: "Masala Dosa",
    desc: "Crispy rice crepe filled with spiced potatoes",
    price: 80,
    category: "South Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 102,
    name: "Plain Dosa",
    desc: "Crispy golden rice and lentil crepe",
    price: 60,
    category: "South Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 103,
    name: "Mysore Masala Dosa",
    desc: "Spicy dosa with red chutney and potato filling",
    price: 90,
    category: "South Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isSpicy: true,
  },
  {
    id: 104,
    name: "Cheese Dosa",
    desc: "Crispy dosa loaded with melted cheese",
    price: 110,
    category: "South Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 105,
    name: "Idli Sambhar (2 Pcs)",
    desc: "Steamed rice cakes with lentil soup",
    price: 60,
    category: "South Indian",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 106,
    name: "Medu Vada (2 Pcs)",
    desc: "Crispy lentil donuts served with sambhar",
    price: 70,
    category: "South Indian",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 107,
    name: "Uttapam",
    desc: "Thick rice pancake with vegetable toppings",
    price: 85,
    category: "South Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 108,
    name: "Rava Dosa",
    desc: "Crispy semolina crepe with onions",
    price: 75,
    category: "South Indian",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
];

// Chinese - Indian Style
export const chineseDishes: MenuItem[] = [
  {
    id: 201,
    name: "Veg Manchurian (Dry)",
    desc: "Crispy vegetable balls tossed in spicy sauce",
    price: 160,
    category: "Chinese",
    type: "Starter",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 202,
    name: "Veg Manchurian (Gravy)",
    desc: "Vegetable balls in thick manchurian gravy",
    price: 180,
    category: "Chinese",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 203,
    name: "Paneer Chilli",
    desc: "Spicy paneer with capsicum and sauces",
    price: 190,
    category: "Chinese",
    type: "Starter",
    image: "/Tarkari-image.png",
    isSpicy: true,
  },
  {
    id: 204,
    name: "Hakka Noodles",
    desc: "Stir-fried noodles with vegetables",
    price: 140,
    category: "Chinese",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 205,
    name: "Schezwan Noodles",
    desc: "Spicy Schezwan sauce tossed noodles",
    price: 150,
    category: "Chinese",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isSpicy: true,
  },
  {
    id: 206,
    name: "Veg Fried Rice",
    desc: "Classic fried rice with mixed vegetables",
    price: 130,
    category: "Chinese",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 207,
    name: "Schezwan Fried Rice",
    desc: "Spicy fried rice with Schezwan flavor",
    price: 140,
    category: "Chinese",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isSpicy: true,
  },
  {
    id: 208,
    name: "Spring Rolls (4 Pcs)",
    desc: "Crispy rolls with vegetable filling",
    price: 120,
    category: "Chinese",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 209,
    name: "Veg Crispy",
    desc: "Crispy fried vegetables in sweet sauce",
    price: 170,
    category: "Chinese",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
];

// Fast Food & Snacks - Mumbai Style
export const snacksDishes: MenuItem[] = [
  {
    id: 301,
    name: "Pav Bhaji",
    desc: "Spicy mashed vegetable curry with buttered pav",
    price: 100,
    category: "Snacks",
    type: "Main Course",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 302,
    name: "Chole Bhature",
    desc: "Spicy chickpeas with fluffy fried bread",
    price: 110,
    category: "Snacks",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 303,
    name: "Veg Sandwich",
    desc: "Grilled sandwich with vegetables and chutneys",
    price: 70,
    category: "Snacks",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 304,
    name: "Cheese Sandwich",
    desc: "Grilled sandwich loaded with cheese",
    price: 90,
    category: "Snacks",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 305,
    name: "Veg Burger",
    desc: "Crispy veg patty with fresh veggies",
    price: 80,
    category: "Snacks",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 306,
    name: "Cheese Burger",
    desc: "Veg patty with melted cheese",
    price: 100,
    category: "Snacks",
    type: "Starter",
    image: "/Tarkari-image.png",
  },
  {
    id: 307,
    name: "Veg Pizza (Regular)",
    desc: "Classic vegetable pizza with cheese",
    price: 150,
    category: "Snacks",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
  {
    id: 308,
    name: "Cheese Pizza (Regular)",
    desc: "Extra cheese pizza with tomato sauce",
    price: 170,
    category: "Snacks",
    type: "Main Course",
    image: "/Tarkari-image.png",
  },
];

// Beverages
export const beverages: MenuItem[] = [
  {
    id: 401,
    name: "Masala Chaas",
    desc: "Spiced buttermilk with herbs",
    price: 40,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 402,
    name: "Sweet Lassi",
    desc: "Traditional yogurt drink with sugar",
    price: 50,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 403,
    name: "Mango Lassi",
    desc: "Creamy mango yogurt drink",
    price: 70,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 404,
    name: "Chocolate Milkshake",
    desc: "Rich chocolate shake with ice cream",
    price: 80,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 405,
    name: "Strawberry Milkshake",
    desc: "Fresh strawberry shake with ice cream",
    price: 80,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 406,
    name: "Mango Milkshake",
    desc: "Creamy mango shake with ice cream",
    price: 80,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 407,
    name: "Falooda",
    desc: "Rose flavored dessert drink with vermicelli",
    price: 90,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 408,
    name: "Fresh Lime Soda",
    desc: "Refreshing lime with soda (Sweet/Salt)",
    price: 50,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
  {
    id: 409,
    name: "Cold Coffee",
    desc: "Chilled coffee with milk and ice cream",
    price: 70,
    category: "Beverages",
    type: "Beverage",
    image: "/Tarkari-image.png",
  },
];

// Thalis - Complete Meals
export const thalis: MenuItem[] = [
  {
    id: 501,
    name: "Regular Thali",
    desc: "2 Sabzi, Dal, Rice, 3 Roti, Salad, Papad, Pickle",
    price: 150,
    category: "Thali",
    type: "Thali",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
  {
    id: 502,
    name: "Special Thali",
    desc: "2 Sabzi, Dal, Rice, 4 Roti, Sweet, Salad, Papad, Raita, Pickle",
    price: 200,
    category: "Thali",
    type: "Thali",
    image: "/Tarkari-image.png",
  },
  {
    id: 503,
    name: "Paneer Thali",
    desc: "Paneer Sabzi, Dal, Rice, 4 Roti, Salad, Papad, Pickle",
    price: 220,
    category: "Thali",
    type: "Thali",
    image: "/Tarkari-image.png",
  },
  {
    id: 504,
    name: "Dal Khichdi",
    desc: "Comfort food - rice and lentils cooked together",
    price: 120,
    category: "Thali",
    type: "Thali",
    image: "/Tarkari-image.png",
    isPopular: true,
  },
];

// Export all dishes combined
export const allMenuItems: MenuItem[] = [
  ...northIndianDishes,
  ...southIndianDishes,
  ...chineseDishes,
  ...snacksDishes,
  ...beverages,
  ...thalis,
];

// Export categories
export const menuCategories = [
  "All",
  "North Indian",
  "South Indian",
  "Chinese",
  "Snacks",
  "Beverages",
  "Thali",
];

export const dishTypes = [
  "All",
  "Starter",
  "Main Course",
  "Breads",
  "Rice",
  "Beverage",
  "Thali",
];
