import connectToDatabase from "../lib/mongodb";
import { Dish } from "../models/Dish";
import { Category } from "../models/Category";

const dishesData = [
  // ==================== NORTH INDIAN ====================
  {
    name: "Paneer Butter Masala",
    slug: "paneer-butter-masala",
    description: "Soft paneer cubes in a creamy tomato-based gravy with butter and cream",
    shortDescription: "Creamy tomato gravy with cottage cheese cubes",
    categoryName: "North Indian",
    pricePaise: 22000, // ₹220
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 320, protein: 18, carbs: 12, fat: 22, fiber: 3 },
    ingredients: ["Paneer", "Tomatoes", "Onions", "Cream", "Butter", "Spices"],
    allergens: ["Dairy"],
  },
  {
    name: "Paneer Tikka",
    slug: "paneer-tikka",
    description: "Marinated cottage cheese grilled to perfection with bell peppers and onions",
    shortDescription: "Marinated cottage cheese grilled to perfection",
    categoryName: "North Indian",
    pricePaise: 24000, // ₹240
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "6 pieces",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 285, protein: 16, carbs: 10, fat: 20, fiber: 2 },
    ingredients: ["Paneer", "Bell Peppers", "Onions", "Yogurt", "Spices"],
    allergens: ["Dairy"],
  },
  {
    name: "Veg Kolhapuri",
    slug: "veg-kolhapuri",
    description: "Spicy mixed vegetables in authentic Kolhapuri style gravy",
    shortDescription: "Spicy mixed vegetables in Kolhapuri style",
    categoryName: "North Indian",
    pricePaise: 20000, // ₹200
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 4,
    servingSize: "1 serving",
    preparationTime: 25,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 180, protein: 6, carbs: 22, fat: 8, fiber: 5 },
    ingredients: ["Mixed Vegetables", "Coconut", "Kolhapuri Masala", "Onions"],
    allergens: [],
  },
  {
    name: "Dal Tadka",
    slug: "dal-tadka",
    description: "Yellow lentils tempered with aromatic spices, garlic and cumin",
    shortDescription: "Yellow lentils tempered with aromatic spices",
    categoryName: "North Indian",
    pricePaise: 16000, // ₹160
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 150, protein: 10, carbs: 20, fat: 4, fiber: 6 },
    ingredients: ["Toor Dal", "Garlic", "Cumin", "Ghee", "Tomatoes"],
    allergens: ["Dairy"],
  },
  {
    name: "Dal Fry",
    slug: "dal-fry",
    description: "Slow-cooked lentils with onion, tomato and aromatic tempering",
    shortDescription: "Slow-cooked lentils with onion and tomato",
    categoryName: "North Indian",
    pricePaise: 15000, // ₹150
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 25,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 145, protein: 9, carbs: 18, fat: 4, fiber: 5 },
    ingredients: ["Mixed Dal", "Onions", "Tomatoes", "Ghee", "Spices"],
    allergens: ["Dairy"],
  },
  {
    name: "Chana Masala",
    slug: "chana-masala",
    description: "Chickpeas cooked in tangy tomato gravy with aromatic spices",
    shortDescription: "Chickpeas in tangy tomato gravy",
    categoryName: "North Indian",
    pricePaise: 18000, // ₹180
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 2,
    servingSize: "1 serving",
    preparationTime: 25,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 210, protein: 12, carbs: 32, fat: 5, fiber: 8 },
    ingredients: ["Chickpeas", "Tomatoes", "Onions", "Chana Masala", "Ginger"],
    allergens: [],
  },
  {
    name: "Aloo Mutter",
    slug: "aloo-mutter",
    description: "Potato and green peas cooked in aromatic onion-tomato gravy",
    shortDescription: "Potato and peas in aromatic gravy",
    categoryName: "North Indian",
    pricePaise: 17000, // ₹170
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 175, protein: 5, carbs: 28, fat: 5, fiber: 4 },
    ingredients: ["Potatoes", "Green Peas", "Tomatoes", "Onions", "Spices"],
    allergens: [],
  },
  {
    name: "Bhendi Do Pyaza",
    slug: "bhendi-do-pyaza",
    description: "Okra cooked with double onions in traditional style",
    shortDescription: "Okra cooked with double onions",
    categoryName: "North Indian",
    pricePaise: 19000, // ₹190
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 120, protein: 3, carbs: 15, fat: 6, fiber: 4 },
    ingredients: ["Okra", "Onions", "Tomatoes", "Spices", "Oil"],
    allergens: [],
  },
  {
    name: "Butter Naan",
    slug: "butter-naan",
    description: "Soft leavened bread brushed with butter, baked in tandoor",
    shortDescription: "Leavened bread brushed with butter",
    categoryName: "North Indian",
    pricePaise: 4000, // ₹40
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 piece",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 282, protein: 9, carbs: 46, fat: 8, fiber: 2 },
    ingredients: ["Flour", "Yogurt", "Yeast", "Butter", "Salt"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Tandoori Roti",
    slug: "tandoori-roti",
    description: "Whole wheat flatbread baked in traditional clay tandoor",
    shortDescription: "Whole wheat flatbread from tandoor",
    categoryName: "North Indian",
    pricePaise: 2500, // ₹25
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 piece",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 106, protein: 4, carbs: 23, fat: 1, fiber: 4 },
    ingredients: ["Whole Wheat Flour", "Water", "Salt"],
    allergens: ["Gluten"],
  },
  {
    name: "Kulcha",
    slug: "kulcha",
    description: "Soft leavened flatbread, perfect with dal or curry",
    shortDescription: "Soft leavened flatbread",
    categoryName: "North Indian",
    pricePaise: 4500, // ₹45
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 piece",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 260, protein: 8, carbs: 42, fat: 7, fiber: 2 },
    ingredients: ["Flour", "Yogurt", "Baking Powder", "Butter"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Jeera Rice",
    slug: "jeera-rice",
    description: "Fragrant basmati rice tempered with cumin seeds and ghee",
    shortDescription: "Basmati rice tempered with cumin",
    categoryName: "North Indian",
    pricePaise: 12000, // ₹120
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 serving",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 210, protein: 4, carbs: 42, fat: 3, fiber: 1 },
    ingredients: ["Basmati Rice", "Cumin Seeds", "Ghee", "Bay Leaf"],
    allergens: ["Dairy"],
  },

  // ==================== SOUTH INDIAN ====================
  {
    name: "Masala Dosa",
    slug: "masala-dosa",
    description: "Crispy rice and lentil crepe filled with spiced potato masala",
    shortDescription: "Crispy rice crepe filled with spiced potatoes",
    categoryName: "South Indian",
    pricePaise: 8000, // ₹80
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 dosa",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 185, protein: 5, carbs: 34, fat: 4, fiber: 2 },
    ingredients: ["Rice", "Urad Dal", "Potatoes", "Onions", "Mustard Seeds"],
    allergens: [],
  },
  {
    name: "Plain Dosa",
    slug: "plain-dosa",
    description: "Crispy golden rice and lentil crepe served with sambar and chutney",
    shortDescription: "Crispy golden rice and lentil crepe",
    categoryName: "South Indian",
    pricePaise: 6000, // ₹60
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 dosa",
    preparationTime: 10,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 150, protein: 4, carbs: 28, fat: 3, fiber: 1 },
    ingredients: ["Rice", "Urad Dal", "Fenugreek Seeds", "Salt"],
    allergens: [],
  },
  {
    name: "Mysore Masala Dosa",
    slug: "mysore-masala-dosa",
    description: "Spicy dosa with red chutney spread and potato filling",
    shortDescription: "Spicy dosa with red chutney and potato filling",
    categoryName: "South Indian",
    pricePaise: 9000, // ₹90
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 3,
    servingSize: "1 dosa",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 210, protein: 6, carbs: 38, fat: 5, fiber: 3 },
    ingredients: ["Rice", "Urad Dal", "Red Chutney", "Potatoes", "Spices"],
    allergens: [],
  },
  {
    name: "Cheese Dosa",
    slug: "cheese-dosa",
    description: "Crispy dosa generously loaded with melted cheese",
    shortDescription: "Crispy dosa loaded with melted cheese",
    categoryName: "South Indian",
    pricePaise: 11000, // ₹110
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 dosa",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 320, protein: 14, carbs: 30, fat: 16, fiber: 1 },
    ingredients: ["Rice", "Urad Dal", "Cheese", "Butter"],
    allergens: ["Dairy"],
  },
  {
    name: "Idli Sambhar (2 Pcs)",
    slug: "idli-sambhar",
    description: "Soft steamed rice cakes served with lentil soup and coconut chutney",
    shortDescription: "Steamed rice cakes with lentil soup",
    categoryName: "South Indian",
    pricePaise: 6000, // ₹60
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "2 pieces",
    preparationTime: 10,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 166, protein: 5, carbs: 31, fat: 2, fiber: 4 },
    ingredients: ["Rice", "Urad Dal", "Toor Dal", "Vegetables", "Tamarind"],
    allergens: [],
  },
  {
    name: "Medu Vada (2 Pcs)",
    slug: "medu-vada",
    description: "Crispy lentil donuts served with sambhar and coconut chutney",
    shortDescription: "Crispy lentil donuts served with sambhar",
    categoryName: "South Indian",
    pricePaise: 7000, // ₹70
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "2 pieces",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 220, protein: 8, carbs: 28, fat: 9, fiber: 3 },
    ingredients: ["Urad Dal", "Curry Leaves", "Green Chilies", "Ginger"],
    allergens: [],
  },
  {
    name: "Uttapam",
    slug: "uttapam",
    description: "Thick rice pancake topped with onions, tomatoes and vegetables",
    shortDescription: "Thick rice pancake with vegetable toppings",
    categoryName: "South Indian",
    pricePaise: 8500, // ₹85
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 uttapam",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 198, protein: 6, carbs: 36, fat: 4, fiber: 3 },
    ingredients: ["Rice", "Urad Dal", "Onions", "Tomatoes", "Capsicum"],
    allergens: [],
  },
  {
    name: "Rava Dosa",
    slug: "rava-dosa",
    description: "Crispy semolina crepe with onions and curry leaves",
    shortDescription: "Crispy semolina crepe with onions",
    categoryName: "South Indian",
    pricePaise: 7500, // ₹75
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 dosa",
    preparationTime: 10,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 180, protein: 4, carbs: 32, fat: 4, fiber: 2 },
    ingredients: ["Semolina", "Rice Flour", "Onions", "Curry Leaves", "Cumin"],
    allergens: ["Gluten"],
  },

  // ==================== CHINESE ====================
  {
    name: "Veg Manchurian (Dry)",
    slug: "veg-manchurian-dry",
    description: "Crispy vegetable balls tossed in spicy Indo-Chinese sauce",
    shortDescription: "Crispy vegetable balls tossed in spicy sauce",
    categoryName: "Chinese",
    pricePaise: 16000, // ₹160
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 2,
    servingSize: "1 serving",
    preparationTime: 18,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 250, protein: 6, carbs: 32, fat: 11, fiber: 3 },
    ingredients: ["Cabbage", "Carrot", "Corn Flour", "Soy Sauce", "Ginger-Garlic"],
    allergens: ["Gluten", "Soy"],
  },
  {
    name: "Veg Manchurian (Gravy)",
    slug: "veg-manchurian-gravy",
    description: "Vegetable balls swimming in thick manchurian gravy",
    shortDescription: "Vegetable balls in thick manchurian gravy",
    categoryName: "Chinese",
    pricePaise: 18000, // ₹180
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 2,
    servingSize: "1 serving",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 280, protein: 7, carbs: 38, fat: 12, fiber: 3 },
    ingredients: ["Cabbage", "Carrot", "Corn Flour", "Soy Sauce", "Spring Onions"],
    allergens: ["Gluten", "Soy"],
  },
  {
    name: "Paneer Chilli",
    slug: "paneer-chilli",
    description: "Spicy paneer cubes with capsicum and onions in chilli sauce",
    shortDescription: "Spicy paneer with capsicum and sauces",
    categoryName: "Chinese",
    pricePaise: 19000, // ₹190
    isVeg: true,
    isVegan: false,
    isSpicy: true,
    spicyLevel: 3,
    servingSize: "1 serving",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 290, protein: 16, carbs: 18, fat: 18, fiber: 2 },
    ingredients: ["Paneer", "Capsicum", "Onions", "Soy Sauce", "Chilli Sauce"],
    allergens: ["Dairy", "Soy"],
  },
  {
    name: "Hakka Noodles",
    slug: "hakka-noodles",
    description: "Stir-fried noodles with mixed vegetables and soy sauce",
    shortDescription: "Stir-fried noodles with vegetables",
    categoryName: "Chinese",
    pricePaise: 14000, // ₹140
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 312, protein: 10, carbs: 55, fat: 7, fiber: 3 },
    ingredients: ["Noodles", "Cabbage", "Carrot", "Spring Onions", "Soy Sauce"],
    allergens: ["Gluten", "Soy"],
  },
  {
    name: "Schezwan Noodles",
    slug: "schezwan-noodles",
    description: "Spicy Schezwan sauce tossed noodles with vegetables",
    shortDescription: "Spicy Schezwan sauce tossed noodles",
    categoryName: "Chinese",
    pricePaise: 15000, // ₹150
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 3,
    servingSize: "1 serving",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 340, protein: 10, carbs: 56, fat: 9, fiber: 3 },
    ingredients: ["Noodles", "Schezwan Sauce", "Vegetables", "Garlic"],
    allergens: ["Gluten", "Soy"],
  },
  {
    name: "Veg Fried Rice",
    slug: "veg-fried-rice",
    description: "Classic fried rice with mixed vegetables and soy sauce",
    shortDescription: "Classic fried rice with mixed vegetables",
    categoryName: "Chinese",
    pricePaise: 13000, // ₹130
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 serving",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 280, protein: 7, carbs: 48, fat: 6, fiber: 2 },
    ingredients: ["Rice", "Cabbage", "Carrot", "Beans", "Soy Sauce"],
    allergens: ["Soy"],
  },
  {
    name: "Schezwan Fried Rice",
    slug: "schezwan-fried-rice",
    description: "Spicy fried rice with Schezwan sauce and vegetables",
    shortDescription: "Spicy fried rice with Schezwan flavor",
    categoryName: "Chinese",
    pricePaise: 14000, // ₹140
    isVeg: true,
    isVegan: true,
    isSpicy: true,
    spicyLevel: 3,
    servingSize: "1 serving",
    preparationTime: 12,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 310, protein: 7, carbs: 50, fat: 8, fiber: 2 },
    ingredients: ["Rice", "Schezwan Sauce", "Vegetables", "Garlic", "Spring Onions"],
    allergens: ["Soy"],
  },
  {
    name: "Spring Rolls (4 Pcs)",
    slug: "spring-rolls",
    description: "Crispy rolls stuffed with mixed vegetable filling",
    shortDescription: "Crispy rolls with vegetable filling",
    categoryName: "Chinese",
    pricePaise: 12000, // ₹120
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "4 pieces",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 220, protein: 5, carbs: 28, fat: 10, fiber: 2 },
    ingredients: ["Spring Roll Sheets", "Cabbage", "Carrot", "Noodles"],
    allergens: ["Gluten"],
  },
  {
    name: "Veg Crispy",
    slug: "veg-crispy",
    description: "Crispy fried vegetables in sweet and spicy sauce",
    shortDescription: "Crispy fried vegetables in sweet sauce",
    categoryName: "Chinese",
    pricePaise: 17000, // ₹170
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 serving",
    preparationTime: 18,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 270, protein: 5, carbs: 35, fat: 12, fiber: 3 },
    ingredients: ["Baby Corn", "Mushrooms", "Capsicum", "Corn Flour", "Honey"],
    allergens: ["Gluten"],
  },

  // ==================== SNACKS ====================
  {
    name: "Pav Bhaji",
    slug: "pav-bhaji",
    description: "Spicy mashed vegetable curry served with buttered pav buns",
    shortDescription: "Spicy mashed vegetable curry with buttered pav",
    categoryName: "Snacks",
    pricePaise: 10000, // ₹100
    isVeg: true,
    isVegan: false,
    isSpicy: true,
    spicyLevel: 2,
    servingSize: "1 serving",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 380, protein: 10, carbs: 52, fat: 15, fiber: 6 },
    ingredients: ["Mixed Vegetables", "Pav Bhaji Masala", "Butter", "Pav"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Chole Bhature",
    slug: "chole-bhature",
    description: "Spicy chickpeas curry served with fluffy deep-fried bread",
    shortDescription: "Spicy chickpeas with fluffy fried bread",
    categoryName: "Snacks",
    pricePaise: 11000, // ₹110
    isVeg: true,
    isVegan: false,
    isSpicy: true,
    spicyLevel: 2,
    servingSize: "1 serving",
    preparationTime: 18,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 450, protein: 14, carbs: 58, fat: 18, fiber: 10 },
    ingredients: ["Chickpeas", "Flour", "Yogurt", "Spices", "Oil"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Veg Sandwich",
    slug: "veg-sandwich",
    description: "Grilled sandwich with fresh vegetables and chutneys",
    shortDescription: "Grilled sandwich with vegetables and chutneys",
    categoryName: "Snacks",
    pricePaise: 7000, // ₹70
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 sandwich",
    preparationTime: 8,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 280, protein: 8, carbs: 38, fat: 11, fiber: 4 },
    ingredients: ["Bread", "Cucumber", "Tomato", "Onion", "Chutney", "Butter"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Cheese Sandwich",
    slug: "cheese-sandwich",
    description: "Grilled sandwich loaded with melted cheese and vegetables",
    shortDescription: "Grilled sandwich loaded with cheese",
    categoryName: "Snacks",
    pricePaise: 9000, // ₹90
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 sandwich",
    preparationTime: 8,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 380, protein: 14, carbs: 36, fat: 20, fiber: 3 },
    ingredients: ["Bread", "Cheese", "Vegetables", "Butter"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Veg Burger",
    slug: "veg-burger",
    description: "Crispy vegetable patty with fresh veggies in a soft bun",
    shortDescription: "Crispy veg patty with fresh veggies",
    categoryName: "Snacks",
    pricePaise: 8000, // ₹80
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 burger",
    preparationTime: 10,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 350, protein: 10, carbs: 42, fat: 15, fiber: 4 },
    ingredients: ["Burger Bun", "Veg Patty", "Lettuce", "Tomato", "Sauce"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Cheese Burger",
    slug: "cheese-burger",
    description: "Veg patty topped with melted cheese in a soft bun",
    shortDescription: "Veg patty with melted cheese",
    categoryName: "Snacks",
    pricePaise: 10000, // ₹100
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 burger",
    preparationTime: 10,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 420, protein: 14, carbs: 40, fat: 22, fiber: 3 },
    ingredients: ["Burger Bun", "Veg Patty", "Cheese", "Lettuce", "Sauce"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Veg Pizza (Regular)",
    slug: "veg-pizza-regular",
    description: "Classic vegetable pizza with cheese and tomato sauce",
    shortDescription: "Classic vegetable pizza with cheese",
    categoryName: "Snacks",
    pricePaise: 15000, // ₹150
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "7 inch",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 450, protein: 16, carbs: 52, fat: 20, fiber: 4 },
    ingredients: ["Pizza Base", "Cheese", "Tomato Sauce", "Vegetables"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Cheese Pizza (Regular)",
    slug: "cheese-pizza-regular",
    description: "Extra cheese pizza with rich tomato sauce",
    shortDescription: "Extra cheese pizza with tomato sauce",
    categoryName: "Snacks",
    pricePaise: 17000, // ₹170
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "7 inch",
    preparationTime: 15,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 520, protein: 20, carbs: 48, fat: 28, fiber: 2 },
    ingredients: ["Pizza Base", "Cheese", "Mozzarella", "Tomato Sauce"],
    allergens: ["Gluten", "Dairy"],
  },

  // ==================== BEVERAGES ====================
  {
    name: "Masala Chaas",
    slug: "masala-chaas",
    description: "Spiced buttermilk with cumin, coriander and herbs",
    shortDescription: "Spiced buttermilk with herbs",
    categoryName: "Beverages",
    pricePaise: 4000, // ₹40
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 glass",
    preparationTime: 3,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 60, protein: 3, carbs: 6, fat: 2, fiber: 0 },
    ingredients: ["Yogurt", "Cumin", "Coriander", "Mint", "Salt"],
    allergens: ["Dairy"],
  },
  {
    name: "Sweet Lassi",
    slug: "sweet-lassi",
    description: "Traditional creamy yogurt drink sweetened with sugar",
    shortDescription: "Traditional yogurt drink with sugar",
    categoryName: "Beverages",
    pricePaise: 5000, // ₹50
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 3,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 150, protein: 5, carbs: 24, fat: 4, fiber: 0 },
    ingredients: ["Yogurt", "Sugar", "Cardamom"],
    allergens: ["Dairy"],
  },
  {
    name: "Mango Lassi",
    slug: "mango-lassi",
    description: "Creamy mango yogurt drink, sweet and refreshing",
    shortDescription: "Creamy mango yogurt drink",
    categoryName: "Beverages",
    pricePaise: 7000, // ₹70
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 3,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 180, protein: 5, carbs: 32, fat: 4, fiber: 1 },
    ingredients: ["Yogurt", "Mango Pulp", "Sugar", "Cardamom"],
    allergens: ["Dairy"],
  },
  {
    name: "Chocolate Milkshake",
    slug: "chocolate-milkshake",
    description: "Rich chocolate shake blended with ice cream and milk",
    shortDescription: "Rich chocolate shake with ice cream",
    categoryName: "Beverages",
    pricePaise: 8000, // ₹80
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 320, protein: 8, carbs: 45, fat: 12, fiber: 2 },
    ingredients: ["Milk", "Chocolate Ice Cream", "Cocoa", "Sugar"],
    allergens: ["Dairy"],
  },
  {
    name: "Strawberry Milkshake",
    slug: "strawberry-milkshake",
    description: "Fresh strawberry shake blended with ice cream",
    shortDescription: "Fresh strawberry shake with ice cream",
    categoryName: "Beverages",
    pricePaise: 8000, // ₹80
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 290, protein: 7, carbs: 42, fat: 10, fiber: 1 },
    ingredients: ["Milk", "Strawberry", "Ice Cream", "Sugar"],
    allergens: ["Dairy"],
  },
  {
    name: "Mango Milkshake",
    slug: "mango-milkshake",
    description: "Creamy mango shake blended with ice cream and milk",
    shortDescription: "Creamy mango shake with ice cream",
    categoryName: "Beverages",
    pricePaise: 8000, // ₹80
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 300, protein: 7, carbs: 48, fat: 10, fiber: 1 },
    ingredients: ["Milk", "Mango", "Ice Cream", "Sugar"],
    allergens: ["Dairy"],
  },
  {
    name: "Falooda",
    slug: "falooda",
    description: "Rose flavored dessert drink with vermicelli, basil seeds and ice cream",
    shortDescription: "Rose flavored dessert drink with vermicelli",
    categoryName: "Beverages",
    pricePaise: 9000, // ₹90
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 8,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 350, protein: 6, carbs: 55, fat: 12, fiber: 2 },
    ingredients: ["Milk", "Rose Syrup", "Vermicelli", "Basil Seeds", "Ice Cream"],
    allergens: ["Dairy", "Gluten"],
  },
  {
    name: "Fresh Lime Soda",
    slug: "fresh-lime-soda",
    description: "Refreshing lime drink with soda - available sweet or salted",
    shortDescription: "Refreshing lime with soda (Sweet/Salt)",
    categoryName: "Beverages",
    pricePaise: 5000, // ₹50
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 3,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 45, protein: 0, carbs: 12, fat: 0, fiber: 0 },
    ingredients: ["Lime", "Soda", "Sugar/Salt", "Mint"],
    allergens: [],
  },
  {
    name: "Cold Coffee",
    slug: "cold-coffee",
    description: "Chilled coffee blended with milk and ice cream",
    shortDescription: "Chilled coffee with milk and ice cream",
    categoryName: "Beverages",
    pricePaise: 7000, // ₹70
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 glass",
    preparationTime: 5,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 220, protein: 6, carbs: 32, fat: 8, fiber: 0 },
    ingredients: ["Coffee", "Milk", "Ice Cream", "Sugar"],
    allergens: ["Dairy"],
  },

  // ==================== THALI ====================
  {
    name: "Regular Thali",
    slug: "regular-thali",
    description: "Complete meal with 2 Sabzi, Dal, Rice, 3 Roti, Salad, Papad, Pickle",
    shortDescription: "2 Sabzi, Dal, Rice, 3 Roti, Salad, Papad, Pickle",
    categoryName: "Thali",
    pricePaise: 15000, // ₹150
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 thali",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 850, protein: 25, carbs: 120, fat: 28, fiber: 15 },
    ingredients: ["Vegetables", "Dal", "Rice", "Wheat Flour", "Salad"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Special Thali",
    slug: "special-thali",
    description: "Premium meal with 2 Sabzi, Dal, Rice, 4 Roti, Sweet, Salad, Papad, Raita, Pickle",
    shortDescription: "2 Sabzi, Dal, Rice, 4 Roti, Sweet, Salad, Papad, Raita, Pickle",
    categoryName: "Thali",
    pricePaise: 20000, // ₹200
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 thali",
    preparationTime: 25,
    imageUrl: "/Tarkari-image.png",
    isFeatured: true,
    isAvailable: true,
    nutrition: { calories: 1050, protein: 30, carbs: 145, fat: 35, fiber: 18 },
    ingredients: ["Vegetables", "Dal", "Rice", "Wheat Flour", "Sweet", "Raita"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Paneer Thali",
    slug: "paneer-thali",
    description: "Paneer lover's meal with Paneer Sabzi, Dal, Rice, 4 Roti, Salad, Papad, Pickle",
    shortDescription: "Paneer Sabzi, Dal, Rice, 4 Roti, Salad, Papad, Pickle",
    categoryName: "Thali",
    pricePaise: 22000, // ₹220
    isVeg: true,
    isVegan: false,
    isSpicy: false,
    spicyLevel: 1,
    servingSize: "1 thali",
    preparationTime: 25,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 980, protein: 35, carbs: 110, fat: 42, fiber: 12 },
    ingredients: ["Paneer", "Vegetables", "Dal", "Rice", "Wheat Flour"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    name: "Dal Khichdi",
    slug: "dal-khichdi",
    description: "Comfort food - rice and lentils cooked together with mild spices",
    shortDescription: "Comfort food - rice and lentils cooked together",
    categoryName: "Thali",
    pricePaise: 12000, // ₹120
    isVeg: true,
    isVegan: true,
    isSpicy: false,
    spicyLevel: 0,
    servingSize: "1 serving",
    preparationTime: 20,
    imageUrl: "/Tarkari-image.png",
    isFeatured: false,
    isAvailable: true,
    nutrition: { calories: 320, protein: 12, carbs: 58, fat: 5, fiber: 6 },
    ingredients: ["Rice", "Moong Dal", "Ghee", "Cumin", "Turmeric"],
    allergens: ["Dairy"],
  },
];

async function seedDishes() {
  try {
    await connectToDatabase();

    console.log("🌱 Starting dish seed...");

    // Clear existing dishes
    await Dish.deleteMany({});
    console.log("✓ Cleared existing dishes");

    // Get all categories
    const categories = await Category.find({}).lean();
    const categoryMap = new Map(
      categories.map((c) => [c.name.toLowerCase(), c._id])
    );

    if (categories.length === 0) {
      console.error("❌ No categories found. Please seed categories first.");
      process.exit(1);
    }

    console.log(`✓ Found ${categories.length} categories`);

    // Seed dishes
    const dishesToInsert = dishesData
      .map((dish) => ({
        ...dish,
        categoryId: categoryMap.get(dish.categoryName.toLowerCase()),
      }))
      .filter((dish) => {
        if (!dish.categoryId) {
          console.warn(`⚠ Category not found for dish: ${dish.name} (${dish.categoryName})`);
          return false;
        }
        return true;
      });

    const result = await Dish.insertMany(dishesToInsert);
    console.log(`✓ Seeded ${result.length} dishes`);

    console.log("\n📊 Dishes by category:");
    const categoryCount: Record<string, number> = {};
    dishesData.forEach((dish) => {
      categoryCount[dish.categoryName] = (categoryCount[dish.categoryName] || 0) + 1;
    });
    Object.entries(categoryCount).forEach(([cat, count]) => {
      console.log(`   ${cat}: ${count} dishes`);
    });

    console.log("\n✅ Dish seeding completed!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error);
    process.exit(1);
  }
}

seedDishes();
